# Generated by Django 4.0.3 on 2022-03-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Mileage',
            new_name='mileage',
        ),
    ]
