# Generated by Django 4.0.3 on 2022-04-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_mileage_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='cars_image'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='cars_image'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='cars_image'),
        ),
    ]
